# Vendored from https://github.com/kristianvast/hermes-claude-auth
# commit 6525928e13a2771ca0fcf0539ea286150e83c421 (2026-08-18), fetched 2026-09-06.
# Unmodified apart from this header. Loaded by ../hermes-claude-auth.nix.
"""
hermes-claude-auth bootstrap — Claude Code OAuth bypass for hermes-agent.
=======================================================================

This file is installed into the hermes-agent venv's site-packages as
``_hermes_claude_auth_bootstrap.py`` by ``install.sh`` or ``install.ps1``.
It is imported at interpreter startup by a sibling ``hermes_claude_auth.pth``
file, then hooks both:

- ``agent.error_classifier`` so Anthropic thinking-replay 400s are classified
  as recoverable before ``agent.conversation_loop`` binds ``classify_api_error``.
- ``agent.anthropic_adapter`` so OAuth billing/tool-name bypass behavior is
  applied immediately after the adapter loads.

Why ``.pth`` + bootstrap rather than ``sitecustomize.py``
---------------------------------------------------------

Debian/Ubuntu ship ``/usr/lib/pythonX.Y/sitecustomize.py`` for apport.  The
system one wins import priority over a venv-local ``sitecustomize.py``, so
installing the hook as ``sitecustomize.py`` silently fails on those
distros — the venv's version is never imported and the bypass is never
loaded.  Fedora/RHEL don't ship a system sitecustomize.py and were
unaffected by the original install pattern.

``.pth`` files are processed by ``site.py`` *before* it imports
``sitecustomize``, regardless of distro.  Lines starting with ``import`` are
exec'd at startup.  Routing through a ``.pth`` shim that imports this
bootstrap sidesteps the apport collision and works identically on every
platform.

To disable: run ``uninstall.sh`` or delete both ``hermes_claude_auth.pth``
and ``_hermes_claude_auth_bootstrap.py`` from the venv's site-packages and
restart hermes-gateway.

DO NOT EDIT THIS FILE IN THE VENV — it will be overwritten on next install.
Edit the source in the hermes-claude-auth repo instead.
"""
# hermes-claude-auth managed — do not remove this marker

from __future__ import annotations

import os
import sys

def _candidate_hermes_homes() -> list[str]:
    """Return every plausible Hermes data dir, most specific first.

    ``HERMES_HOME`` may point at a *profile* directory
    (``...\\hermes\\profiles\\<name>``) rather than the install root.
    Patches are installed once at the root, so a profile-scoped
    HERMES_HOME must still fall back to the root — otherwise the
    bypass silently fails to import (ModuleNotFoundError).
    """
    homes: list[str] = []

    def _add(path: str | None) -> None:
        if path:
            p = os.path.abspath(os.path.expanduser(path))
            if p not in homes:
                homes.append(p)

    configured = os.environ.get("HERMES_HOME")
    _add(configured)

    # If HERMES_HOME is a profile dir, walk up past 'profiles/<name>'.
    if configured:
        p = os.path.abspath(os.path.expanduser(configured))
        parent = os.path.dirname(p)
        if os.path.basename(parent).lower() == "profiles":
            _add(os.path.dirname(parent))

    if os.name == "nt":
        local_app_data = os.environ.get("LOCALAPPDATA")
        if local_app_data:
            _add(os.path.join(local_app_data, "hermes"))
    _add("~/.hermes")
    return homes


def _default_hermes_home() -> str:
    """Backwards-compatible single-value resolver."""
    homes = _candidate_hermes_homes()
    return homes[0] if homes else os.path.expanduser("~/.hermes")


def _resolve_patches_dir() -> str:
    """Pick the first patches dir that actually contains the bypass module."""
    explicit = os.environ.get("HERMES_PATCHES_DIR")
    if explicit:
        return os.path.expanduser(explicit)

    fallback = None
    for home in _candidate_hermes_homes():
        cand = os.path.join(home, "patches")
        if fallback is None:
            fallback = cand
        if os.path.isfile(os.path.join(cand, "anthropic_billing_bypass.py")):
            return cand
    return fallback or os.path.join(_default_hermes_home(), "patches")


_PATCHES_DIR = _resolve_patches_dir()
_TARGET_MODULE = "agent.anthropic_adapter"

if os.path.isdir(_PATCHES_DIR) and _PATCHES_DIR not in sys.path:
    sys.path.insert(0, _PATCHES_DIR)


def _make_import_hook(target_module, patcher_fn, label):  # type: ignore[no-untyped-def]
    try:
        from importlib.abc import MetaPathFinder
        from importlib.util import find_spec
    except ImportError:
        return

    class _ClaudeCodeBypassFinder(MetaPathFinder):
        _patched = False

        def find_spec(self, fullname, path=None, target=None):  # type: ignore[override]
            if fullname != target_module or self._patched:
                return None

            # Temporarily remove ourselves to avoid recursion during find_spec.
            if self in sys.meta_path:
                sys.meta_path.remove(self)
            try:
                spec = find_spec(fullname)
            finally:
                if self not in sys.meta_path:
                    sys.meta_path.insert(0, self)

            if spec is None or spec.loader is None:
                return None

            original_exec = getattr(spec.loader, "exec_module", None)
            if not callable(original_exec):
                return None

            finder = self

            def patched_exec(module):  # type: ignore[no-untyped-def]
                original_exec(module)
                finder._patched = True
                try:
                    patcher_fn(module)
                except Exception as exc:
                    import traceback

                    sys.stderr.write(
                        f"[{label}] bypass failed: {type(exc).__name__}: {exc}\n"
                    )
                    traceback.print_exc(file=sys.stderr)

            spec.loader.exec_module = patched_exec  # type: ignore[attr-defined]
            return spec

    sys.meta_path.insert(0, _ClaudeCodeBypassFinder())


def _load_billing_bypass():  # type: ignore[no-untyped-def]
    try:
        import anthropic_billing_bypass
    except ImportError:
        return None
    return anthropic_billing_bypass


def _patch_anthropic_adapter(module):  # type: ignore[no-untyped-def]
    anthropic_billing_bypass = _load_billing_bypass()
    if anthropic_billing_bypass is None:
        return

    ok = anthropic_billing_bypass.apply_patches(module)
    if not ok:
        sys.stderr.write(
            "[hermes-claude-auth] bypass declined "
            "(API incompatibility detected)\n"
        )


def _patch_error_classifier(_module):  # type: ignore[no-untyped-def]
    anthropic_billing_bypass = _load_billing_bypass()
    if anthropic_billing_bypass is None:
        return

    anthropic_billing_bypass._install_thinking_replay_classifier_patch()


def _install_hook() -> None:
    _make_import_hook(_TARGET_MODULE, _patch_anthropic_adapter, "hermes-claude-auth")


def _install_all_hooks() -> None:
    # error_classifier must be hooked before agent.conversation_loop binds
    # classify_api_error, or thinking-replay 400s stay classified as fatal.
    _make_import_hook(
        "agent.error_classifier",
        _patch_error_classifier,
        "hermes-claude-auth-errors",
    )
    _install_hook()


try:
    _install_all_hooks()
except Exception as _exc:
    sys.stderr.write(f"[hermes-claude-auth] hook install failed: {_exc}\n")
