esphome:
  name: $name
  friendly_name: $friendly_name

esp8266:
  board: esp8285
  restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$name"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80


climate:
  - platform: heatpumpir
    name: $name
    protocol: mitsubishi_msy
    horizontal_default: middle
    vertical_default: up
    min_temperature: 16
    max_temperature: 31
    receiver_id: rcvr

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

remote_receiver:
  id: rcvr
  pin:
    number: GPIO5
    inverted: true
  dump: all

