esphome:
  name: chris
  friendly_name: chris

esp32:
  variant: esp32
  # restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: "The Cosy 2.4G"
  # fast_connect: true  # disables scan (not needed for a single network)

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "chris"
    password: "chris123"

captive_portal:

web_server:
  port: 80


sensor:
  - platform: hdc1080
    temperature:
      id: dht_temp
      name: Temperature
      filters:
      - offset: -1.0
    humidity:
      id: dht_humidity
      name: Humidity
    update_interval: 60s


remote_transmitter:
  id: ir_tx
  pin: GPIO18
  carrier_duty_percent: 50%

remote_receiver:
  id: ir_rx
  pin:
   number: GPIO19
   inverted: true
   mode:
    input: true
    pullup: true


i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

climate:
  - platform: climate_ir_lg
    name: "AC"
    sensor: dht_temp


# light:
#   - platform: rgb
#     name: Blue LED
#     id: led
#     blue: light_output2
#     green: light_output1
#     red: light_output3
#   - platform: status_led
#     name: Green LED
#     id: led2
#     output: light_output1


# output:
#   - id: light_output1
#     platform: ledc
#     pin:
#       number: GPIO16
#       inverted: true
#   - id: light_output2
#     platform: ledc
#     pin:
#       number: GPIO17
#       inverted: true
#   - id: light_output3
#     platform: ledc
#     pin:
#       number: GPIO4
#       inverted: true
