#!/usr/bin/env python3
"""Persist current Wayland output configuration as a niri kdl fragment.

Reads the live output state from `niri msg --json outputs` and writes a
configuration to ~/.config/niri/displays.kdl that, when included from
config.kdl (e.g. via `include "displays.kdl"` or by copy-paste), reproduces
the current geometry. Intended workflow:

    1. arrange displays interactively with `wdisplays`
    2. run this script to snapshot the result
    3. niri picks up the persisted config on next reload / restart

Notes on the niri JSON schema (see niri ipc.rs):
  - logical:        { x, y, width, height, scale, transform } | null
  - modes[i]:       { width, height, refresh_rate (mHz), is_preferred }
  - current_mode:   index into modes | null
  - logical == null => output disabled => emit `off`
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

# Map niri-ipc Transform serde tags -> niri kdl tokens (see niri-ipc lib.rs
# `impl FromStr for Transform`). Serde uses the variant name verbatim except
# for the explicitly renamed rotation variants ("90"/"180"/"270").
_TRANSFORM_KDL = {
    "Normal": "normal",
    "90": "90",
    "180": "180",
    "270": "270",
    "Flipped": "flipped",
    "Flipped90": "flipped-90",
    "Flipped180": "flipped-180",
    "Flipped270": "flipped-270",
}


def fetch_outputs() -> dict[str, dict[str, Any]]:
    try:
        proc = subprocess.run(
            ["niri", "msg", "--json", "outputs"],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        sys.exit("error: `niri` not found in PATH; run inside a niri session")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"error: `niri msg` failed: {exc.stderr.strip() or exc}")

    data = json.loads(proc.stdout)
    if not isinstance(data, dict):
        sys.exit("error: unexpected niri ipc payload (expected object)")
    return data


def fmt_refresh(mhz: int) -> str:
    # niri accepts e.g. "60.000"; three decimals match niri msg --json.
    return f"{mhz / 1000:.3f}"


def fmt_scale(scale: float) -> str:
    # Drop trailing zeros so 1.0 -> "1" but keep precision otherwise.
    s = f"{scale:.6f}".rstrip("0").rstrip(".")
    return s or "1"


def kdl_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_output(name: str, out: dict[str, Any]) -> str:
    lines: list[str] = [f'output "{kdl_escape(name)}" {{']

    logical = out.get("logical")
    if logical is None:
        lines.append("    off")
        lines.append("}")
        return "\n".join(lines)

    modes = out.get("modes") or []
    cur_idx = out.get("current_mode")
    if isinstance(cur_idx, int) and 0 <= cur_idx < len(modes):
        m = modes[cur_idx]
        mode_str = f'{m["width"]}x{m["height"]}@{fmt_refresh(int(m["refresh_rate"]))}'
        lines.append(f'    mode "{mode_str}"')

    scale = logical.get("scale")
    if scale is not None:
        lines.append(f"    scale {fmt_scale(float(scale))}")

    transform = logical.get("transform")
    kdl_transform = _TRANSFORM_KDL.get(transform) if isinstance(transform, str) else None
    if transform is not None and kdl_transform is None:
        sys.exit(f"error: unknown transform {transform!r} from niri ipc")
    if kdl_transform is not None and kdl_transform != "normal":
        lines.append(f'    transform "{kdl_transform}"')

    x = logical.get("x")
    y = logical.get("y")
    if x is not None and y is not None:
        lines.append(f"    position x={int(x)} y={int(y)}")

    if out.get("vrr_enabled"):
        lines.append("    variable-refresh-rate")

    lines.append("}")
    return "\n".join(lines)


def render(outputs: dict[str, dict[str, Any]]) -> str:
    header = (
        "// Auto-generated by scripts/save-niri-displays.py.\n"
        "// Snapshot of `niri msg --json outputs` -- do not edit by hand;\n"
        "// re-run the script after rearranging displays in wdisplays.\n"
    )
    blocks = [render_output(name, outputs[name]) for name in sorted(outputs)]
    return header + "\n".join(blocks) + "\n"


def default_path() -> Path:
    # Match niri's own `~` expansion, which uses home_dir() (see
    # niri-config/src/lib.rs include handling). Do NOT honour
    # XDG_CONFIG_HOME here -- niri's include directive does not.
    return Path.home() / ".config" / "niri" / "displays.kdl"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=default_path(),
        help="destination file (default: ~/.config/niri/displays.kdl)",
    )
    ap.add_argument(
        "--stdout",
        action="store_true",
        help="print the rendered kdl to stdout instead of writing the file",
    )
    args = ap.parse_args()

    rendered = render(fetch_outputs())

    if args.stdout:
        sys.stdout.write(rendered)
        return

    args.output.parent.mkdir(parents=True, exist_ok=True)
    tmp = args.output.with_suffix(args.output.suffix + ".tmp")
    tmp.write_text(rendered)
    os.replace(tmp, args.output)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
