[fish-ai]
configuration = local-llama
debug = True
log = /tmp/fish-ai.log
system_prompt = """
Don't justify
Don't explain
"""
codify_prompt = """
Don't provide alternatives
Provide just the command. No code blocks (```)
"""

[local-llama]
provider = self-hosted
; model = ministral-3:8b
; model = Qwen2.5-Coder:7b
; model = gpt-oss
model = qwen3-coder-next
server = http://bam.d:11434/v1
