{lib, ... }: {
  allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "claude-code"
    "steam"
    "steam-original"
    "steam-runtime"
    "steam-run"
    "steam-unwrapped"
    "vscode"
    "vscode-extension-ms-vscode-cpptools"
    "vscode-extension-github-copilot"
    "vscode-extension-github-copilot-chat"
    # "vscode-extension-MS-python-vscode-pylance"
    # "vscode-extension-ms-python-vscode-pylance"
    "vscode-extension-ms-vsliveshare-vsliveshare"
    "zerotierone"
    "Oracle_VM_VirtualBox_Extension_Pack"
    # NVIDIA / CUDA
    "cuda_cccl"
    "cuda_cudart"
    "cuda_cuobjdump"
    "cuda_cupti"
    "cuda_cuxxfilt"
    "cuda_gdb"
    "cuda_nvcc"
    "cuda_nvdisasm"
    "cuda_nvml_dev"
    "cuda_nvprune"
    "cuda_nvrtc"
    "cuda_nvtx"
    "cuda_profiler_api"
    "cuda_sanitizer_api"
    "cuda-merged"
    "cudnn"
    "libcublas"
    "libcufft"
    "libcufile"
    "libcurand"
    "libcusolver"
    "libcusparse_lt"
    "libcusparse"
    "libnpp"
    "libnvjitlink"
    "nvidia-settings"
    "nvidia-x11"
  ];
}
